# Generated by Django 5.1.7 on 2025-03-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0003_alter_assignment_id_alter_excelfile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='分数'),
        ),
    ]
